# docker-compose.yaml
version: '3.1'
services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  worker:
    environment:
      - REDIS_URL=redis://redis:6379
      - USE_DB_AUTHENTICATION=false
    image: plb/firecrawl-worker:local
    pull_policy: always
    restart: always

  server:
    environment:
      - REDIS_URL=redis://redis:6379
      - USE_DB_AUTHENTICATION=false
      - HOST=0.0.0.0
    image: plb/firecrawl-server:local
    pull_policy: always
    ports:
      - "3002:3002"
    restart: always
    
volumes:
  redis_data:
